# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: clorin <clorin@student.42.fr>              +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2023/07/25 11:25:31 by clorin            #+#    #+#              #
#    Updated: 2023/09/26 08:47:33 by clorin           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

RESULT = ft_turing

SOURCES = 	types.ml \
			colors.ml \
			utils.ml \
			tape.mli tape.ml \
			parsing.ml \
			machine.mli machine.ml \
			interactive_mode.ml \
			main.ml
LIBS = yojson
OCAMLMAKEFILE = ../OCamlMakefile
include $(OCAMLMAKEFILE)
