# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: clorin <clorin@student.42.fr>              +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2023/07/25 11:25:31 by clorin            #+#    #+#              #
#    Updated: 2023/09/11 10:59:23 by clorin           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

RESULT = test
SOURCES = colors.ml utils.ml machine.ml main.ml
LIBS = yojson
OCAMLMAKEFILE = ../OCamlMakefile
include $(OCAMLMAKEFILE)
